name: comic_book
description: "A new Flutter project based on SQLite + Provider demo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:        
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\fonts\Kanit,Noto_Sans_Thai\Kanit\Kanit-Regular.ttf
  fonts:
    - family: Kanit
      fonts:
        - asset: assets\fonts\Kanit,Noto_Sans_Thai\Kanit\Kanit-Regular.ttf




